[build-system]
requires = ["setuptools >= 65.4.0", "setuptools_scm[toml]>=7.0.5"]
build-backend = "setuptools.build_meta"

[project]
name = "model_benchmark_zoo"
authors = [
  { name="Jonathan Shimwell", email="mail@jshimwell.com" },
]
license = {file = "LICENSE.txt"}
description = "Collection of geometries for testing neutronics simulations in CSG and CAD format"
readme = "README.md"
requires-python = ">=3.10"
keywords = ["dagmc", "geometry", "test", "benchmark"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = []
dynamic = ["version"]


[tool.setuptools_scm]
write_to = "src/_version.py"


[project.optional-dependencies]
tests = [
    "pytest"
]

[project.urls]
"Homepage" = "https://github.com/fusion-energy/model_benchmark_zoo"
"Bug Tracker" = "https://github.com/fusion-energy/model_benchmark_zoo/issues"

[tool.setuptools]
package-dir = {"" = "src"}
